# Generated by Django 4.1.4 on 2022-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.TextField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
